name: Deploy to cpanel

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout del código
        uses: actions/checkout@v4

      - name: ⚙️ Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 📦 Instalar dependencias
        run: npm install

      - name: 🏗️ Construir el proyecto Astro
        run: npm run build

      - name: 🚀 Desplegar a cPanel vía SFTP (con Llave SSH)
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USERNAME }}
          ssh_private_key: ${{ secrets.SFTP_SSH_KEY }}
          port: 22222
          local_path: './dist/*'
          remote_path: './public_html/sushi/'